<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Compte;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Compte>
 */
class CompteFactory extends Factory
{
    protected $model = Compte::class;

    public function definition(): array
    {
        return [
            // numero_compte will be generated by model if absent
            'numero_compte' => null,
            'user_id' => null, // should be supplied or created with relationship
            'solde' => $this->faker->randomFloat(2, 0, 10000),
            'status' => 'actif',
        ];
    }
}
